spring:
  application:
    name: rental_tomo

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  thymeleaf:
    cache: false
  sql:
    init:
      data-locations: classpath:data.sql
      mode: never


jwt:
  token:
    secret: ${JWT_SECRET}
    access_expiration : 3600000
    refresh_expiration : 604800000


logging:
  level:
    org.springframework.security: DEBUG

server:
  ssl:
    enabled: true
    key-store: src/main/resources/bootsecurity.p12
    key-store-password: ${SSL_PWD}
    key-store-type: PKCS12
    key-alias: bootsecurity
  port: 9999